version: "3.3"
networks:
   gamein:
     external: true


services:
  front:
    image: front
    container_name: front
    restart: always
    ports:
      - 3000:3000
    networks:
      - gamein   
