version: "3.3"
networks:
   gamein:
     external: true


services:
  front:
    image: registry.dariasystem.com/gamein/front:dev
    container_name: front
    restart: always
    ports:
      - 3000:80
    networks:
      - gamein 
      
  front-1:
    image: registry.dariasystem.com/gamein/front:dev
    container_name: front-1
    restart: always
    ports:
      - 3000:80
    networks:
      - gamein  
